services:
  # 1. Генератор данных
  generator:
    build: .
    container_name: shop_generator
    ports:
      - "8000:8000"

  # 2. Сборщик (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: shop_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"

  # 3. Визуализация (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: shop_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

# Описание тома для хранения данных (на одном уровне с services)
volumes:
  prometheus_data:
  grafana_data: